version: '3'
services:
  web:
    build: .
    ports:
     - "192.168.51.28:8443:8443"
    networks:
     - spring
  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    ports:
      - "192.168.51.28:6379:6379"
    networks:
      - spring
  mongo:
    image: mongo
    command: [ "mongod"]
    ports:
      - "192.168.51.28:27017:27017"
    networks:
      - spring
networks:
  spring:
    external: true
